version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./conf:/app/conf:ro
    depends_on:
      - redis
    networks:
      - job-finder-network

  # Streamlit Frontend
  web:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - job-finder-network

  # Kedro Pipeline Runner
  kedro:
    build:
      context: .
      dockerfile: kedro.Dockerfile
    environment:
      - ENV=development
    volumes:
      - ./conf:/app/conf:ro
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - job-finder-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - job-finder-network

  # Development tools (optional)
  jupyter:
    build:
      context: .
      dockerfile: kedro.Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./:/app
      - ./data:/app/data
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    networks:
      - job-finder-network

volumes:
  redis_data:

networks:
  job-finder-network:
    driver: bridge
