version: '3.8'

services:
  # Development API with hot reload
  api-dev:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - RELOAD=true
    volumes:
      - ./:/app
      - ./conf:/app/conf:ro
    command: uvicorn web_app.backend.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis-dev
    networks:
      - job-finder-dev

  # Development Streamlit with hot reload
  web-dev:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api-dev:8000
    volumes:
      - ./:/app
    command: streamlit run web_app/frontend/app.py --server.address 0.0.0.0
    depends_on:
      - api-dev
    networks:
      - job-finder-dev

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - job-finder-dev

  # Jupyter Lab for development
  jupyter-dev:
    build:
      context: .
      dockerfile: kedro.Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./:/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    networks:
      - job-finder-dev

networks:
  job-finder-dev:
    driver: bridge