apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
spec:
  type: NodePort
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
