name: CI

description: >
  Run code quality, type checks, tests, and local Docker builds on all branches and PRs.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  precommit:
    name: 🧹 Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: astral-sh/setup-uv@v3
        with:
          version: latest
      - run: make install
      - run: uv run pre-commit run --all-files

  test:
    name: 🧪 Tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
        with:
          version: latest
      - run: make install
      - run: make test-cov
      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.9'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  docker-build-test:
    name: 🐳 Docker Build (local, no push)
    runs-on: ubuntu-latest
    needs: [precommit, test]
    strategy:
      matrix:
        service: [base, fastapi, frontend, kedro]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service }}.Dockerfile
          push: false
          tags: job-finder-${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
