name: CI for job_finder

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  PYTHON_VERSION: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install packages
        run: |
          make install

      - name: Run Pytest
        run: |
          echo "Running tests"
          make test

      - name: Run pylint and fail if score < 7.0
        run: |
          echo "Running pylint..."
          uv run pylint src/ tests/
