name: Deploy Docker Images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag to use'
        required: true
        default: 'latest'
      deploy_kedro:
        description: 'Deploy Kedro image'
        required: false
        type: boolean
        default: true
      deploy_streamlit:
        description: 'Deploy Streamlit image'
        required: false
        type: boolean
        default: true
      deploy_fastapi:
        description: 'Deploy FastAPI image'
        required: false
        type: boolean
        default: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Streamlit image
        if: ${{ github.event.inputs.deploy_streamlit == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: streamlit.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/job_finder_streamlit:${{ github.event.inputs.tag }}

      - name: Build and push Kedro image
        if: ${{ github.event.inputs.deploy_kedro == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: kedro.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/job_finder_kedro:${{ github.event.inputs.tag }}

      - name: Build and push FastAPI image
        if: ${{ github.event.inputs.deploy_fastapi == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: fastapi.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/job_finder_fastapi:${{ github.event.inputs.tag }}
